### ISSUE TITLE
Поддержка environment на глобальном уровне

### ISSUE THREAD

**Issue by sergeyzwezdin** [yandex-cloud/serverless-plugin#111]
Если передать переменные окружения на уровне функции, то они задаются для функции после развертывания:

```yml
service: yandex-cloud-nodejs
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16
  httpApi:
    payload: '1.0'

plugins:
  - "@yandex-cloud/serverless-plugin"

functions:
  simple:
    handler: dist/index.hello
    memorySize: 128
    timeout: '5'
    account: function-sa
    environment:
      TEST: 1
    events:
      - http:
          method: post
          path: /post/just/to/this/path

```

Но если задавать их глобально, то после развертывания для функции они не появляются:

```yml
service: yandex-cloud-nodejs
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16
  httpApi:
    payload: '1.0'
  environment:
    TEST: 1

plugins:
  - "@yandex-cloud/serverless-plugin"

functions:
  simple:
    handler: dist/index.hello
    memorySize: 128
    timeout: '5'
    account: function-sa
    events:
      - http:
          method: post
          path: /post/just/to/this/path

```

Хотелось бы иметь возможность задать их одновременно для всех функций.
