### ISSUE TITLE
Plugin doesn't provide a validation schema for its config

### ISSUE THREAD

**Issue by IlyaSemenov** [yandex-cloud/serverless-plugin#17]
Create `serverless.yaml`:

```yaml
service: test

provider:
  name: yandex-cloud
  runtime: nodejs14

plugins:
  - serverless-yandex-cloud

package:
  patterns:
    - dist/*.js

functions:
  api:
    handler: dist.index.handler
    memory: 128
    timeout: 5
```

Run:

```
serverless deploy
```

Result:

```
❯ serverless deploy
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Configuration warning: Unrecognized provider 'yandex-cloud'
Serverless:
Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
Serverless: You may turn off this message with "configValidationMode: off" setting
```

___

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.0.0
     Framework Version:         2.43.0 (local)
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.0
```
