### ISSUE TITLE
Версия Serverless

### ISSUE THREAD

**Issue by LevanKvirkvelia** [yandex-cloud/serverless-plugin#3]
Если устанавливать по инструкции, то дефолтно устанавливается Serverless >2.0.0

Деплой выдает ошибку: The Serverless version (2.4.0) does not satisfy the "frameworkVersion" (>=1.1.0 <2.0.0) in serverless.yml

Если убрать ограничение, то все работает

Не стал делать ПР т.к. не уверен, что кроме обновления версии ничего не надо менять

**Comment by antonydevanchi** [comment]
Ну... Надо бы еще плагин написать, собсна :D

**Comment by gbougakov** [comment]
Если убрать из конфига строку с ограничением, то ругается немного, но работает

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Configuration warning: Unrecognized provider 'yandex-cloud'
Serverless:  
Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
Serverless: You may turn off this message with "configValidationMode: off" setting
Serverless:  
Serverless: Configuration warning:
Serverless:   at root: unrecognized property 'name'
Serverless:   at root: unrecognized property 'resources'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
      Maybe you should set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY environment variables
Serverless: Service account created
            trigger-sa: aje9l0o3s0583a13evhc
Serverless: Unknonwn function "rbtk-getstate" found
Serverless: Unknonwn function "quasar-trigger-scenario" found
Serverless: Unknonwn function "test" found
Serverless: Unknonwn function "test-py" found
Serverless: Unknonwn function "rbtk-homebridge-bridge" found
Serverless: Function created
            simple: nodejs-dev-simple
Serverless: Service deployed successfully

**************************************************************************************************************************************
Serverless: Announcing Metrics, CI/CD, Secrets and more built into Serverless Framework. Run "serverless login" to activate for free..
**************************************************************************************************************************************
```
