### ISSUE TITLE
AWS resources are created without the project prefix

### ISSUE THREAD

**Issue by esseswann** [yandex-cloud/serverless-plugin#74]
When using AWS SQS client the queue created lacks the project prefix. Might be the case for all AWS compatible resources that use non-yc SDK

**Comment by nikolaymatrosov** [comment]
It is worth to be fixed for queues. But it might not be accurate for buckets. As their names are used as globally unique identifiers, it is more obvious to define them explicitly. Also, another case related to bucket names: if a bucket is used to store a static site, the bucket name should match the site's domain name. So implicit changes could break the rule. If you need to define bucket names based on the project name, you should use the variable interpolation serverless framework provides. E.g.
 ```yaml
resources:
  SomeBucket:
    type: yc::ObjectStorageBucket
    name: '${self:service}-bucket'
 ```
